### ISSUE TITLE
Test  Android-JS

### ISSUE THREAD

**Issue by wanghuan1115** [sdkbox/sdkbox-vungle-sample#5]
### 编译出错

错误信息:

~~~
-post-compile:

-obfuscate:

-dex:
      [dex] input: /Users/gbox/Documents/chukong_test/sdkbox-vungle-sample/js/frameworks/runtime-src/proj.android/bin/classes
      [dex] input: /Users/gbox/Documents/chukong_test/sdkbox-vungle-sample/js/frameworks/cocos2d-x/cocos/platform/android/java/bin/classes.jar
      [dex] input: /Users/gbox/Documents/chukong_test/sdkbox-vungle-sample/google-play-services_lib/bin/classes.jar
      [dex] input: /Users/gbox/Documents/chukong_test/sdkbox-vungle-sample/js/frameworks/cocos2d-x/cocos/platform/android/java/libs/javax.inject-1.jar
      [dex] input: /Users/gbox/Documents/chukong_test/sdkbox-vungle-sample/js/frameworks/cocos2d-x/cocos/platform/android/java/libs/vungle-publisher-adaptive-id-3.3.2.jar
      [dex] input: /Users/gbox/Documents/chukong_test/sdkbox-vungle-sample/js/frameworks/cocos2d-x/cocos/platform/android/java/libs/PluginVungle.jar
      [dex] input: /Users/gbox/Documents/chukong_test/sdkbox-vungle-sample/js/frameworks/cocos2d-x/cocos/platform/android/java/libs/dagger-1.2.2.jar
      [dex] input: /Users/gbox/Documents/chukong_test/sdkbox-vungle-sample/js/frameworks/cocos2d-x/cocos/platform/android/java/libs/nineoldandroids-2.4.0.jar
      [dex] input: /Users/gbox/Documents/chukong_test/sdkbox-vungle-sample/js/frameworks/cocos2d-x/cocos/platform/android/java/libs/support-v4-18.0.0.jar
      [dex] input: /Users/gbox/Documents/chukong_test/sdkbox-vungle-sample/google-play-services_lib/libs/google-play-services.jar
      [dex] input: /Users/gbox/Documents/chukong_test/sdkbox-vungle-sample/js/frameworks/cocos2d-x/cocos/platform/android/java/libs/sdkbox.jar
      [dex] input: /Users/gbox/Documents/chukong_test/sdkbox-vungle-sample/js/frameworks/cocos2d-x/cocos/platform/android/java/libs/vungle-publisher-adaptive-id-3.3.3.jar
      [dex] Pre-Dexing /Users/gbox/Documents/chukong_test/sdkbox-vungle-sample/js/frameworks/cocos2d-x/cocos/platform/android/java/bin/classes.jar -> classes-52446ef961b44415d06c14c291d033eb.jar
      [dex] Pre-Dexing /Users/gbox/Documents/chukong_test/sdkbox-vungle-sample/google-play-services_lib/bin/classes.jar -> classes-72711d05ae7594cb93e04447d61928dc.jar
      [dex] Pre-Dexing /Users/gbox/Documents/chukong_test/sdkbox-vungle-sample/js/frameworks/cocos2d-x/cocos/platform/android/java/libs/javax.inject-1.jar -> javax.inject-1-763734ad19f116dd4e1b0aef7e2cdc1b.jar
      [dex] Pre-Dexing /Users/gbox/Documents/chukong_test/sdkbox-vungle-sample/js/frameworks/cocos2d-x/cocos/platform/android/java/libs/vungle-publisher-adaptive-id-3.3.2.jar -> vungle-publisher-adaptive-id-3.3.2-9f29adb690e4879b9b87602af420f373.jar
      [dex] Pre-Dexing /Users/gbox/Documents/chukong_test/sdkbox-vungle-sample/js/frameworks/cocos2d-x/cocos/platform/android/java/libs/PluginVungle.jar -> PluginVungle-01ec11fe8077e4d1313c582bc62241b4.jar
      [dex] Pre-Dexing /Users/gbox/Documents/chukong_test/sdkbox-vungle-sample/js/frameworks/cocos2d-x/cocos/platform/android/java/libs/dagger-1.2.2.jar -> dagger-1.2.2-312b650c2f93e7a7a291bc364250afbf.jar
      [dex] Pre-Dexing /Users/gbox/Documents/chukong_test/sdkbox-vungle-sample/js/frameworks/cocos2d-x/cocos/platform/android/java/libs/nineoldandroids-2.4.0.jar -> nineoldandroids-2.4.0-ce0030938358a8e0f65e20b62a228da6.jar
      [dex] Pre-Dexing /Users/gbox/Documents/chukong_test/sdkbox-vungle-sample/js/frameworks/cocos2d-x/cocos/platform/android/java/libs/support-v4-18.0.0.jar -> support-v4-18.0.0-fcb3ee72eecf4e42fc1540ba37488a53.jar
      [dex] Pre-Dexing /Users/gbox/Documents/chukong_test/sdkbox-vungle-sample/google-play-services_lib/libs/google-play-services.jar -> google-play-services-346852ef11e34d49b00103be36274cff.jar
      [dex] Pre-Dexing /Users/gbox/Documents/chukong_test/sdkbox-vungle-sample/js/frameworks/cocos2d-x/cocos/platform/android/java/libs/sdkbox.jar -> sdkbox-6003ccb5dbf04bb4adefa13019ab7cbb.jar
      [dex] Pre-Dexing /Users/gbox/Documents/chukong_test/sdkbox-vungle-sample/js/frameworks/cocos2d-x/cocos/platform/android/java/libs/vungle-publisher-adaptive-id-3.3.3.jar -> vungle-publisher-adaptive-id-3.3.3-f073e5551b04cb26e2b55f5cd0bcf262.jar
      [dex] Converting compiled files and external libraries into /Users/gbox/Documents/chukong_test/sdkbox-vungle-sample/js/frameworks/runtime-src/proj.android/bin/classes.dex...
       [dx] Merged dex A (22 defs/20.6KiB) with dex B (88 defs/111.1KiB). Result is 110 defs/154.7KiB. Took 0.1s
       [dx] Merged dex A (110 defs/154.7KiB) with dex B (1 defs/0.4KiB). Result is 111 defs/193.2KiB. Took 0.0s
       [dx] Merged dex A (111 defs/193.2KiB) with dex B (6 defs/1.6KiB). Result is 117 defs/261.4KiB. Took 0.0s
       [dx] Merged dex A (117 defs/261.4KiB) with dex B (714 defs/547.3KiB). Result is 831 defs/1045.1KiB. Took 0.1s
       [dx] Merged dex A (831 defs/1045.1KiB) with dex B (6 defs/6.3KiB). Result is 837 defs/1460.3KiB. Took 0.1s
       [dx] Result compacted from 2276.9KiB to 721.7KiB to save 1555.2KiB
       [dx] Merged dex A (837 defs/1460.3KiB) with dex B (44 defs/53.8KiB). Result is 881 defs/721.7KiB. Took 0.2s
       [dx] Merged dex A (881 defs/721.7KiB) with dex B (73 defs/100.8KiB). Result is 954 defs/1001.4KiB. Took 0.0s
       [dx] Merged dex A (954 defs/1001.4KiB) with dex B (444 defs/491.7KiB). Result is 1398 defs/1895.3KiB. Took 0.1s
       [dx] Result compacted from 8277.1KiB to 6107.8KiB to save 2169.3KiB
       [dx] Merged dex A (1398 defs/1895.3KiB) with dex B (5610 defs/4845.3KiB). Result is 7008 defs/6107.8KiB. Took 0.7s
       [dx]
       [dx] UNEXPECTED TOP-LEVEL EXCEPTION:
       [dx] com.android.dex.DexException: Multiple dex files define Lcom/vungle/log/Logger;
       [dx] Result compacted from 7329.6KiB to 6144.2KiB to save 1185.4KiB	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:594)
       [dx]
       [dx] 	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:552)
       [dx] Merged dex A (7008 defs/6107.8KiB) with dex B (38 defs/47.0KiB). Result is 7046 defs/6144.2KiB. Took 0.4s	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:533)
       [dx]
       [dx] 	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:170)
       [dx] 	at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
       [dx] 	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:439)
       [dx] 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:287)
       [dx] 	at com.android.dx.command.dexer.Main.run(Main.java:230)
       [dx] 	at com.android.dx.command.dexer.Main.main(Main.java:199)
       [dx] 	at com.android.dx.command.Main.main(Main.java:103)
       [dx]

BUILD FAILED
/Users/gbox/Android/sdk/tools/ant/build.xml:888: The following error occurred while executing this line:
/Users/gbox/Android/sdk/tools/ant/build.xml:890: The following error occurred while executing this line:
/Users/gbox/Android/sdk/tools/ant/build.xml:902: The following error occurred while executing this line:
/Users/gbox/Android/sdk/tools/ant/build.xml:283: null returned: 2

Total time: 56 seconds
执行命令出错，返回值：1。
~~~

**Comment by yinjimmy** [comment]
```
./obj/local/armeabi/libjscocos2d.a: No space left on device
```

你本地已经没有磁盘空间了
